#!/bin/bash

export QUDA_GPU_ARCH=sm_61
export TRILINOS_HOME=/home/astrel/Work/Libs/install
#export OMPI_CXX=${TRILINOS_HOME}/bin/nvcc_wrapper

cmake .. -DCMAKE_CXX_COMPILER=mpicxx \
	-DCMAKE_EXE_LINKER_FLAGS_INIT="-L/usr/local/cuda-9.2/lib64 -lnvrtc" \
	-DQUDA_DIRAC_WILSON=ON \
	-DQUDA_DIRAC_CLOVER=ON \
	-DQUDA_DIRAC_STAGGERED=OFF \
	-DQUDA_DIRAC_DOMAIN_WALL=OFF \
	-DQUDA_DIRAC_TWISTED_MASS=OFF \
	-DQUDA_BUILD_SHAREDLIB=ON \
	-DQUDA_LINK_HISQ=OFF \
	-DQUDA_FORCE_GAUGE=OFF \
	-DQUDA_FORCE_HISQ=OFF \
	-DQUDA_MPI=ON \
	-DQUDA_QMP=OFF \
	-DQUDA_QMPHOME="/opt/scidac-gcc-7.3.0-ompi-3.1.2" \
	-DQUDA_QIO=OFF \
	-DQUDA_QIOHOME="/opt/scidac-gcc-7.3.0-ompi-3.1.2" \
	-DQUDA_LIMEHOME="/opt/scidac-gcc-7.3.0-ompi-3.1.2" \
	-DQUDA_DIRAC_TWISTED_CLOVER=OFF \
	-DQUDA_MULTIGRID=OFF\
	-DQUDA_INTERFACE_MILC=OFF \
	-DCUDA_cublas_LIBRARY=/usr/local/cuda-9.2/lib64/libcublas.so \
	-DQUDA_USE_EIGEN=ON \
	-DEIGEN_INCLUDE_DIR=/opt/eigen-3.3.4/include/eigen3 \
	-DQUDA_DOWNLOAD_EIGEN=OFF \
	-DQUDA_JITIFY=OFF \
	-DQUDA_JULIA=ON \
	-DQUDA_TRILINOS=OFF \
	-DTrilinos_PREFIX:PATH=$TRILINOS_HOME \
	-DCMAKE_BUILD_TYPE=HOSTDEBUG 
