name: rocm-build-ci
run-name: ${{ github.actor }} is kicking off a ROCm build
on: pull_request
jobs:
  rocm-build:
    runs-on: [self-hosted, amd]
    steps:
      - uses: actions/checkout@v3
      - run: |
          export ROCM_PATH=/opt/rocm-5.5.0
          export PATH=${ROCM_PATH}/bin:${ROCM_PATH}/llvm/bin:${PATH}
          SRCROOT=`pwd`
          BUILDROOT=`mktemp -d build-XXXXXXXX`
          INSTALLROOT=`mktemp -d install-XXXXXXXX`
          QUDA_GPU_ARCH=gfx90a
          cmake ${SRCROOT} \
            -B ${BUILDROOT} \
            -DQUDA_TARGET_TYPE="HIP" \
            -DQUDA_GPU_ARCH=${QUDA_GPU_ARCH} \
            -DROCM_PATH=${ROCM_PATH} \
            -DQUDA_DIRAC_CLOVER=ON \
            -DQUDA_DIRAC_CLOVER_HASENBUSCH=OFF \
            -DQUDA_DIRAC_DOMAIN_WALL=OFF \
            -DQUDA_DIRAC_NDEG_TWISTED_MASS=OFF \
            -DQUDA_DIRAC_STAGGERED=ON \
            -DQUDA_DIRAC_TWISTED_MASS=OFF \
            -DQUDA_DIRAC_TWISTED_CLOVER=OFF \
            -DQUDA_DIRAC_WILSON=ON \
            -DQUDA_CLOVER_DYNAMIC=ON \
            -DQUDA_QDPJIT=OFF \
            -DQUDA_INTERFACE_QDPJIT=OFF \
            -DQUDA_INTERFACE_MILC=ON \
            -DQUDA_INTERFACE_CPS=OFF \
            -DQUDA_INTERFACE_QDP=ON \
            -DQUDA_INTERFACE_TIFR=OFF \
            -DQUDA_QMP=ON \
            -DQUDA_DOWNLOAD_USQCD=ON \
            -DQUDA_OPENMP=OFF \
            -DQUDA_MULTIGRID=ON \
            -DQUDA_DOWNLOAD_EIGEN=ON \
            -DQUDA_PRECISION=14 \
            -DCMAKE_INSTALL_PREFIX=${INSTALLROOT} \
            -DCMAKE_BUILD_TYPE="DEVEL" \
            -DCMAKE_CXX_COMPILER="${ROCM_PATH}/llvm/bin/clang++" \
            -DCMAKE_C_COMPILER="${ROCM_PATH}/llvm/bin/clang" \
            -DCMAKE_HIP_COMPILER="${ROCM_PATH}/llvm/bin/clang++" \
            -DBUILD_SHARED_LIBS=ON \
            -DQUDA_BUILD_SHAREDLIB=ON \
            -DQUDA_BUILD_ALL_TESTS=ON \
            -DQUDA_CTEST_DISABLE_BENCHMARKS=ON \
            -DCMAKE_C_STANDARD=99
          cmake --build ${BUILDROOT} -j 16
          cmake --install ${BUILDROOT}
          rm -rf ${BUILDROOT}
          rm -rf ${INSTALLROOT}
